title = 'Johns Tech Hub'
baseURL = 'https://johnski001.com/'
languageCode = 'en-us'
theme = 'ananke'
enableRobotsTXT = true

[pagination]
pagerSize = 10

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
